# JuliaによるLU分解の計算

行列$A$のLU分解は `LinearAlgebra`パッケージの`lu(A)`関数で計算できる．

In [5]:
using LinearAlgebra
A = Float64[1 2 3; 1 4 9; 1 8 27];
L,U = lu(A,NoPivot())  

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 1.0  1.0  0.0
 1.0  3.0  1.0
U factor:
3×3 Matrix{Float64}:
 1.0  2.0  3.0
 0.0  2.0  6.0
 0.0  0.0  6.0

In [6]:
L*U == A   # 確認

true

これで `L`, `U` に$A$のLU分解の行列が格納される．

#### 【注意】
上の例で `lu(A)` ではなく `lu(A,NoPivot())`
としているのは後述する pivoting を行わないように指定するためである．

pivotingを有効にすると$L, U$が三角行列のならないので，今の場合は
pivotingを無効にしている．

通常は，pivotingを有効にしたほうがよい
（例えば，精度や計算速度の向上が期待できる）．

In [38]:
L,U,piv = lu(A)  # `piv` に pivotingによる行交換の情報が格納される

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0  0.0       0.0
 1.0  1.0       0.0
 1.0  0.333333  1.0
U factor:
3×3 Matrix{Float64}:
 1.0  2.0   3.0
 0.0  6.0  24.0
 0.0  0.0  -2.0

In [29]:
L*U == A   # 確認

false

In [30]:
piv

3-element Vector{Int64}:
 1
 3
 2

これは 2行目と3行目が交換されたことを示唆している．

In [36]:
P = zeros(size(A))   # 同じサイズのゼロ行列生成
for i in 1:size(A)[1]
   P[i,piv[i]] = 1
end
P

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.0  1.0
 0.0  1.0  0.0

In [39]:
P*L*U == A    

true